base_url = "https://nmbr7.github.io"

title = "nmbr7"
description = "Adventurer"
generate_feeds = true

compile_sass = true

taxonomies = [
    {name = "tags", feed = false},
]


[link_checker]
skip_anchor_prefixes = []
internal_level = "warn"

[extra]
author = "Suhailr7"
